cms: &cms
  adapter: mysql2
  database: reactor_test
  username: reactor_user
  password: reactor_user
  host: 127.0.0.1
  port: 23306
  reconnect: true

test:
  <<: *cms

production:
  <<: *cms

development:
  #<<: *cms
  adapter: mysql2
  database: reactor_test_ugd
  username: root
  password: root
  host: 127.0.0.1
  port: 23306
  reconnect: true
